[package]
name = "rinha-03"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
[dependencies.redis]
git = "https://github.com/redis-rs/redis-rs.git"
