services:
  instance_01:
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha_instance_01
    expose:
      - "3000"
    environment:
      - SERVER_ID=instance_01
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
  instance_02:
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha_instance_02
    expose:
      - "3000"
    environment:
      - SERVER_ID=instance_02
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
  nginx:
    image: nginx:alpine
    container_name: rinha_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - instance_01
      - instance_02
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: rinha_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - backend


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true