services:
  instance_01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha_instance_01
    expose:
      - "3000"
    environment:
      - SERVER_ID=instance_01
  instance_02:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rinha_instance_02
    expose:
      - "3000"
    environment:
      - SERVER_ID=instance_02
  nginx:
    image: nginx:alpine
    container_name: rinha_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - instance_01
      - instance_02
  redis:
    image: redis:alpine
    container_name: rinha_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
